generate_reqs:
	echo "\`define k 4" > ring_req4.v
	cat ring_req.v >> ring_req4.v
	echo "\`define k 4" > ring_req4f.v
	cat ring_req_f.v >> ring_req4f.v	
	echo "\`define k 8" > ring_req8.v
	cat ring_req.v >> ring_req8.v
	echo "\`define k 8" > ring_req8f.v
	cat ring_req_f.v >> ring_req8f.v		
	echo "\`define k 16" > ring_req16.v
	cat ring_req.v >> ring_req16.v
	echo "\`define k 16" > ring_req16f.v
	cat ring_req_f.v >> ring_req16f.v		
	echo "\`define k 32" > ring_req32.v
	cat ring_req.v >> ring_req32.v
	echo "\`define k 32" > ring_req32f.v
	cat ring_req_f.v >> ring_req32f.v		